name: Keep Supabase Project Active

on:
  schedule:
    # This runs at 00:00 every Monday and Thursday
    - cron: '0 0 * * 1,4'
  workflow_dispatch: # Allows you to run it manually for testing

jobs:
  ping_supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Send Request to Supabase API
        run: |
          curl -i -X GET "${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}/rest/v1/" \
          -H "apikey: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}"
